# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/bagseongbu/Desktop/CU Boulder/NS_web_server"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/bagseongbu/Desktop/CU Boulder/NS_web_server"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/bagseongbu/Desktop/CU Boulder/NS_web_server/CMakeFiles" "/Users/bagseongbu/Desktop/CU Boulder/NS_web_server//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/bagseongbu/Desktop/CU Boulder/NS_web_server/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/fs/docroot.o: src/fs/docroot.cc.o
.PHONY : src/fs/docroot.o

# target to build an object file
src/fs/docroot.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/fs/docroot.cc.o
.PHONY : src/fs/docroot.cc.o

src/fs/docroot.i: src/fs/docroot.cc.i
.PHONY : src/fs/docroot.i

# target to preprocess a source file
src/fs/docroot.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/fs/docroot.cc.i
.PHONY : src/fs/docroot.cc.i

src/fs/docroot.s: src/fs/docroot.cc.s
.PHONY : src/fs/docroot.s

# target to generate assembly for a file
src/fs/docroot.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/fs/docroot.cc.s
.PHONY : src/fs/docroot.cc.s

src/fs/sendfile.o: src/fs/sendfile.cc.o
.PHONY : src/fs/sendfile.o

# target to build an object file
src/fs/sendfile.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/fs/sendfile.cc.o
.PHONY : src/fs/sendfile.cc.o

src/fs/sendfile.i: src/fs/sendfile.cc.i
.PHONY : src/fs/sendfile.i

# target to preprocess a source file
src/fs/sendfile.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/fs/sendfile.cc.i
.PHONY : src/fs/sendfile.cc.i

src/fs/sendfile.s: src/fs/sendfile.cc.s
.PHONY : src/fs/sendfile.s

# target to generate assembly for a file
src/fs/sendfile.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/fs/sendfile.cc.s
.PHONY : src/fs/sendfile.cc.s

src/http/mime_map.o: src/http/mime_map.cc.o
.PHONY : src/http/mime_map.o

# target to build an object file
src/http/mime_map.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/mime_map.cc.o
.PHONY : src/http/mime_map.cc.o

src/http/mime_map.i: src/http/mime_map.cc.i
.PHONY : src/http/mime_map.i

# target to preprocess a source file
src/http/mime_map.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/mime_map.cc.i
.PHONY : src/http/mime_map.cc.i

src/http/mime_map.s: src/http/mime_map.cc.s
.PHONY : src/http/mime_map.s

# target to generate assembly for a file
src/http/mime_map.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/mime_map.cc.s
.PHONY : src/http/mime_map.cc.s

src/http/pipeline_queue.o: src/http/pipeline_queue.cc.o
.PHONY : src/http/pipeline_queue.o

# target to build an object file
src/http/pipeline_queue.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/pipeline_queue.cc.o
.PHONY : src/http/pipeline_queue.cc.o

src/http/pipeline_queue.i: src/http/pipeline_queue.cc.i
.PHONY : src/http/pipeline_queue.i

# target to preprocess a source file
src/http/pipeline_queue.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/pipeline_queue.cc.i
.PHONY : src/http/pipeline_queue.cc.i

src/http/pipeline_queue.s: src/http/pipeline_queue.cc.s
.PHONY : src/http/pipeline_queue.s

# target to generate assembly for a file
src/http/pipeline_queue.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/pipeline_queue.cc.s
.PHONY : src/http/pipeline_queue.cc.s

src/http/request.o: src/http/request.cc.o
.PHONY : src/http/request.o

# target to build an object file
src/http/request.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/request.cc.o
.PHONY : src/http/request.cc.o

src/http/request.i: src/http/request.cc.i
.PHONY : src/http/request.i

# target to preprocess a source file
src/http/request.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/request.cc.i
.PHONY : src/http/request.cc.i

src/http/request.s: src/http/request.cc.s
.PHONY : src/http/request.s

# target to generate assembly for a file
src/http/request.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/request.cc.s
.PHONY : src/http/request.cc.s

src/http/response.o: src/http/response.cc.o
.PHONY : src/http/response.o

# target to build an object file
src/http/response.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/response.cc.o
.PHONY : src/http/response.cc.o

src/http/response.i: src/http/response.cc.i
.PHONY : src/http/response.i

# target to preprocess a source file
src/http/response.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/response.cc.i
.PHONY : src/http/response.cc.i

src/http/response.s: src/http/response.cc.s
.PHONY : src/http/response.s

# target to generate assembly for a file
src/http/response.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http/response.cc.s
.PHONY : src/http/response.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/server/accept_loop.o: src/server/accept_loop.cc.o
.PHONY : src/server/accept_loop.o

# target to build an object file
src/server/accept_loop.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/accept_loop.cc.o
.PHONY : src/server/accept_loop.cc.o

src/server/accept_loop.i: src/server/accept_loop.cc.i
.PHONY : src/server/accept_loop.i

# target to preprocess a source file
src/server/accept_loop.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/accept_loop.cc.i
.PHONY : src/server/accept_loop.cc.i

src/server/accept_loop.s: src/server/accept_loop.cc.s
.PHONY : src/server/accept_loop.s

# target to generate assembly for a file
src/server/accept_loop.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/accept_loop.cc.s
.PHONY : src/server/accept_loop.cc.s

src/server/conn_manager.o: src/server/conn_manager.cc.o
.PHONY : src/server/conn_manager.o

# target to build an object file
src/server/conn_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/conn_manager.cc.o
.PHONY : src/server/conn_manager.cc.o

src/server/conn_manager.i: src/server/conn_manager.cc.i
.PHONY : src/server/conn_manager.i

# target to preprocess a source file
src/server/conn_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/conn_manager.cc.i
.PHONY : src/server/conn_manager.cc.i

src/server/conn_manager.s: src/server/conn_manager.cc.s
.PHONY : src/server/conn_manager.s

# target to generate assembly for a file
src/server/conn_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/conn_manager.cc.s
.PHONY : src/server/conn_manager.cc.s

src/util/log.o: src/util/log.cc.o
.PHONY : src/util/log.o

# target to build an object file
src/util/log.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/util/log.cc.o
.PHONY : src/util/log.cc.o

src/util/log.i: src/util/log.cc.i
.PHONY : src/util/log.i

# target to preprocess a source file
src/util/log.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/util/log.cc.i
.PHONY : src/util/log.cc.i

src/util/log.s: src/util/log.cc.s
.PHONY : src/util/log.s

# target to generate assembly for a file
src/util/log.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/util/log.cc.s
.PHONY : src/util/log.cc.s

src/util/strutil.o: src/util/strutil.cc.o
.PHONY : src/util/strutil.o

# target to build an object file
src/util/strutil.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/util/strutil.cc.o
.PHONY : src/util/strutil.cc.o

src/util/strutil.i: src/util/strutil.cc.i
.PHONY : src/util/strutil.i

# target to preprocess a source file
src/util/strutil.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/util/strutil.cc.i
.PHONY : src/util/strutil.cc.i

src/util/strutil.s: src/util/strutil.cc.s
.PHONY : src/util/strutil.s

# target to generate assembly for a file
src/util/strutil.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/util/strutil.cc.s
.PHONY : src/util/strutil.cc.s

src/util/timer.o: src/util/timer.cc.o
.PHONY : src/util/timer.o

# target to build an object file
src/util/timer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/util/timer.cc.o
.PHONY : src/util/timer.cc.o

src/util/timer.i: src/util/timer.cc.i
.PHONY : src/util/timer.i

# target to preprocess a source file
src/util/timer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/util/timer.cc.i
.PHONY : src/util/timer.cc.i

src/util/timer.s: src/util/timer.cc.s
.PHONY : src/util/timer.s

# target to generate assembly for a file
src/util/timer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/util/timer.cc.s
.PHONY : src/util/timer.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... src/fs/docroot.o"
	@echo "... src/fs/docroot.i"
	@echo "... src/fs/docroot.s"
	@echo "... src/fs/sendfile.o"
	@echo "... src/fs/sendfile.i"
	@echo "... src/fs/sendfile.s"
	@echo "... src/http/mime_map.o"
	@echo "... src/http/mime_map.i"
	@echo "... src/http/mime_map.s"
	@echo "... src/http/pipeline_queue.o"
	@echo "... src/http/pipeline_queue.i"
	@echo "... src/http/pipeline_queue.s"
	@echo "... src/http/request.o"
	@echo "... src/http/request.i"
	@echo "... src/http/request.s"
	@echo "... src/http/response.o"
	@echo "... src/http/response.i"
	@echo "... src/http/response.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/server/accept_loop.o"
	@echo "... src/server/accept_loop.i"
	@echo "... src/server/accept_loop.s"
	@echo "... src/server/conn_manager.o"
	@echo "... src/server/conn_manager.i"
	@echo "... src/server/conn_manager.s"
	@echo "... src/util/log.o"
	@echo "... src/util/log.i"
	@echo "... src/util/log.s"
	@echo "... src/util/strutil.o"
	@echo "... src/util/strutil.i"
	@echo "... src/util/strutil.s"
	@echo "... src/util/timer.o"
	@echo "... src/util/timer.i"
	@echo "... src/util/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

